language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: 2.0/.vuepress/dist
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
