language: node_js
node_js:
  - lts/*
install:
  - yarn
script:
  - yarn run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: EasyDingTalk/easydingtalk.github.io
  keep-history: true
  target-branch: master
  fqdn: docs.easydingtalk.org
  committer_from_gh: true
  on:
    branch: 2.0
