language: node_js
node_js:
  - lts/*
install:
  - npm install
script:
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN
  repo: EasyDingTalk/easydingtalk.github.io
  keep-history: true
  target-branch: master
  on:
    branch: 2.0
